version: "3.5"

services: 
    postgres:
        image: postgres:latest
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_DB: dev
            POSTGRES_PASSWORD: postgres

    user:
        image: store/user-api
        ports: 
            - "8080:8080"
        environment: 
            POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
            POSTGRES_DB: dev
            POSTGRES_PASSWORD: postgres        
        depends_on:
            - postgres

    product:
        image: store/product-api
        ports: 
            - "8081:8081"
        environment: 
            POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
            POSTGRES_DB: dev
            POSTGRES_PASSWORD: postgres 
        depends_on:
            - postgres                   
            
    shopping:
        image: store/shopping-api
        ports: 
            - "8082:8082"
        environment: 
            POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
            POSTGRES_DB: dev
            POSTGRES_PASSWORD: postgres                
        depends_on: 
            - postgres            